### ISSUE TITLE
Hot Reloading on docker

### ISSUE THREAD

**Issue by srijan-esm** [esmagico/devops#21]
## dockerfile.local
```
# Stage 1: Build
FROM node:18 AS build

WORKDIR /usr/src/app

# Install libvips dependencies
RUN apt-get update && apt-get install -y \
libvips libvips-dev && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

ARG NEXT_PUBLIC_EPIC_BASE_URL
ARG NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL
ARG NEXT_PUBLIC_EPIC_IMAGE_BASE_URL

# Check if the required build arguments are provided
RUN : "${NEXT_PUBLIC_EPIC_BASE_URL:?Build argument NEXT_PUBLIC_EPIC_BASE_URL is required}"\
    && : "${NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL:?Build argument NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL is required}"\
    && : "${NEXT_PUBLIC_EPIC_IMAGE_BASE_URL:?Build argument NEXT_PUBLIC_EPIC_IMAGE_BASE_URL is required}"

# Set environment variables
ENV NEXT_PUBLIC_EPIC_BASE_URL=$NEXT_PUBLIC_EPIC_BASE_URL
ENV NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL=$NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL
ENV NEXT_PUBLIC_EPIC_IMAGE_BASE_URL=$NEXT_PUBLIC_EPIC_IMAGE_BASE_URL

COPY package-lock.json package.json ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

```

docker-compose.yaml

```
services:
  epic_global_fronted:
    build: 
      context: .
      dockerfile: Dockerfile.local
      args:
        NEXT_PUBLIC_EPIC_BASE_URL: ${NEXT_PUBLIC_EPIC_BASE_URL:?NEXT_PUBLIC_EPIC_BASE_URL is not set}
        NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL: ${NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL:?NEXT_PUBLIC_EPIC_CONTRACT_BASE_URL is not set}
        NEXT_PUBLIC_EPIC_IMAGE_BASE_URL: ${NEXT_PUBLIC_EPIC_IMAGE_BASE_URL:?NEXT_PUBLIC_EPIC_IMAGE_BASE_URL is not set}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

```
